# Specify the workspace image configuration
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Database setup
    init: |
      gp await-port 5432
      psql < setup.sql
      gp sync-done dbsetup
  - name: Superset setup
    init: |
      export SUPERSET_CONFIG_PATH=$PWD/superset/superset_config.py
      export PIP_USER=false
      python -m venv superset/.venv
      source superset/.venv/bin/activate
      pip install Pillow
      pip install psycopg2
      pip install apache-superset
      gb sync-await dbsetup
      superset db upgrade
      superset fab create-admin --username admin --firstname admin --lastname admin --email your@email.com --password admin
      superset init
      superset import-datasources -p superset/datasources.yml
    command: |
      export SUPERSET_CONFIG_PATH=$PWD/superset/superset_config.py
      source superset/.venv/bin/activate
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
  - name: Meltano setup
    env:
      PIP_USER: false
    init: |
      export PIP_USER=false
      cd meltano
      python3 -m venv .venv
      source .venv/bin/activate
      mkdir .meltano
      pip install meltano
      meltano install
    command: |
      cd meltano
      source .venv/bin/activate    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8088
    onOpen: open-browser
    visibility: private
  - port: 5432
    onOpen: ignore
    visibility: private