title: Data Stacks For Fun & Nonprofits
author: Andrew Stewart
# logo: logo.png
execute:
  execute_notebooks: off
only_build_toc_files: true
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", .venv, "meltano/.meltano/**"]
repository:
  url: https://github.com/andrewcstewart/ds4fnp
html:
  use_repository_button: true