version: '3.3'

services:
  superset:
    image: apache/superset
    # see: https://hub.docker.com/r/apache/superset
    ports:
      - 8080:8088
    volumes:
      - .gitpod/superset:/setup:rw

  db:
    image: postgres
    # see https://hub.docker.com/_/postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .gitpod/postgres:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_PASSWORD: admin

  dbt-docs:
    image: nginx
    ports:
        - 8000:80
    volumes:
        - /workspace/meltano/.meltano/transformers/dbt/target:/usr/share/nginx/html      

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - db:postgres  # my database container is called postgres, not db
    environment:
      # - DATABASE_URL=postgres://ds4fnp:ds4fnp@postgres:5432/ds4fnp?sslmode=disable
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/ds4fnp?sslmode=disable
    depends_on:
      - db        